# Generated by Django 5.0.7 on 2024-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TSC_Number', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Rensponsibility', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('phone_number', models.PositiveIntegerField(max_length=100)),
            ],
        ),
    ]
